@api = http://localhost:4000/products
GET {{api}} 
Content-Type: application/json
###
POST {{api}} 
Content-Type: application/json

{
    "name": "microfone",
    "description": "microfone samsung",
    "quantity": "12"
}

### //getProductByid
GET {{api}}/4


### //DeleteProductByid
DELETE {{api}}/11

### //getTotalProducts
GET {{api}}/count

### //updateProductByid
PUT {{api}}/9
Content-Type: application/json

{
    "name": "keyboard",
    "description": "Asus",
    "quantity": "5"
}